name: cine6

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  yayin:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
    - name: 📥 Depoyu klonla
      uses: actions/checkout@v4
      
    - name: 🐍 Python kurulumu
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: 📦 FFmpeg ve Kurulumlar
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends ffmpeg ca-certificates openssl
        pip install requests
        
    - name: 🚀 Yayını başlat
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: python cine6.py
